coffeeine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path, include
from main.views import show_main, create_item, show_xml, show_json, show_xml_by_id, show_json_by_id, \
                       register, login_user, logout_user, edit_item, delete_item, get_item_json, add_item_ajax, \
                       increment_item_ajax, decrement_item_ajax, delete_item_ajax, create_item_flutter
from . import views

app_name = 'main'

urlpatterns = [
     path('', show_main, name='show_main'),
     path('create-item', create_item, name='create_item'),
     path('xml/', show_xml, name='show_xml'), 
     path('json/', show_json, name='show_json'), 
     path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
     path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
     path('register/', register, name='register'),
     path('login/', login_user, name='login'),
     path('logout/', logout_user, name='logout'),
     path('edit-item/<int:id>', edit_item, name='edit_item'),
     path('delete/<int:id>', delete_item, name='delete_item'),
     path('get-item/', get_item_json, name='get_item_json'),
     path('create-ajax/', add_item_ajax, name='add_item_ajax'),
     path('increment-item-ajax/<int:id>/', increment_item_ajax, name='increment_item_ajax'),
     path('decrement-item-ajax/<int:id>/', decrement_item_ajax, name='decrement_item_ajax'),
     path('delete-item-ajax/<int:id>/', delete_item_ajax, name='delete_item_ajax'),
     path('create-flutter/', create_item_flutter, name='create_item_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    amount = models.IntegerField()
    description = models.TextField()

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "price", "amount", "description"]

main/views.py
import json
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.core import serializers
from main.forms import ItemForm
from main.models import Item
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseNotFound

@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user=request.user)

    context = {
        'name': request.user.username, 
        'class': 'PBP C', 
        'items': items,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_item.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_item(request, id):
    # Get item berdasarkan ID
    item = Item.objects.get(pk = id)

    # Set item sebagai instance dari form
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_item.html", context)

def delete_item(request, id):
    # Get data berdasarkan ID
    item = Item.objects.get(pk = id)
    # Hapus data
    item.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

def get_item_json(request):
    item = Item.objects.filter(user = request.user)
    return HttpResponse(serializers.serialize('json', item))

@csrf_exempt
def add_item_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        price = request.POST.get("price")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_item = Item(name=name, price=price, amount=amount, description=description, user=user)
        new_item.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def increment_item_ajax(request, id):
    item = Item.objects.get(pk=id)
    item.amount += 1
    item.save()
    return HttpResponse(b"DELETED", status=201)

@csrf_exempt
def decrement_item_ajax(request, id):
    item = Item.objects.get(pk=id)
    item.amount -= 1
    if item.amount <= 0:
        item.amount = 0
    item.save()
    return HttpResponse(b"DELETED", status=201)

@csrf_exempt
def delete_item_ajax(request, id):
    item = Item.objects.get(pk=id)
    item.delete()
    return HttpResponse(b"DELETED", status=201)

@csrf_exempt
def create_item_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            price = int(data["price"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block meta %}
        {% endblock meta %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
        <link rel="stylesheet" type="text/css" href="style.css">
    </head>

    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>

main/templates/create_item.html
{% extends 'base.html' %}

{% block meta %}
    <title>Add New Coffee</title>
{% endblock meta %}

{% block content %}
<style>
    .navbar {
        background-color: #000;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        padding: 20px 50px;
        margin-bottom: 40px;
    }

    .navbar-brand img {
        width: 80px; 
        height: 80px;
        margin-right: 10px; 
    }

    .navbar-brand {
        font-size: 60px;
        font-family: "EB Garamond", serif;
        color: #ffffff;
        text-align: center;
        padding-top: 10px;
    }

    .navbar-brand:hover {
        color: #ffffff;
    }

    .btn-primary {
        background-color: green;
        border-color: darkgreen;
        margin-bottom: 15px;
    }

    .btn-primary:hover, .btn-primary:active, .btn-primary:focus {
        background-color: darkgreen;
        border-color: darkgreen;
    }

    .btn-secondary {
        background-color: black;
        margin-bottom: 15px;
    }

    .btn-secondary:hover, .btn-secondary:active, .btn-secondary:focus {
        background-color: #2b2a2a;
    }

    .card-header {
        text-align: center;
    }

</style>

    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="https://i.imgur.com/S4xLOxr.png" alt="Logo" class="d-inline-block align-text-top">
                Coffeeine.
            </a>
        </div>
    </nav>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header"><h1>Add Your New Coffee</h1></div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <table class="table">
                                {{ form.as_table }}
                                <tr>
                                    <td></td>
                                    <td>
                                        <input class="btn btn-primary" type="submit" value="Add Coffee">
                                        <a class="btn btn-secondary" href="{% url 'main:show_main' %}">Cancel</a>
                                    </td>
                                </tr>
                            </table>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

main/templates/edit_item.html
{% extends 'base.html' %}

{% block meta %}
    <title>Edit Coffee</title>
{% endblock meta %}

{% block content %}
<style>
    .navbar {
        background-color: #000;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        padding: 20px 50px;
        margin-bottom: 40px;
    }

    .navbar-brand img {
        width: 80px; 
        height: 80px;
        margin-right: 10px; 
    }

    .navbar-brand {
        font-size: 60px;
        font-family: "EB Garamond", serif;
        color: #ffffff;
        text-align: center;
        padding-top: 10px;
    }

    .navbar-brand:hover {
        color: #ffffff;
    }

    .btn-primary, .btn-primary:active, .btn-primary:focus {
        background-color: #eb8921;
        border-color: #eb8921;
        margin-bottom: 15px;
    }

    .btn-primary:hover{
        background-color: #f5ad28;
        border-color: #f5ad28;
    }

    .btn-secondary {
        background-color: black;
        margin-bottom: 15px;
    }

    .btn-secondary:hover, .btn-secondary:active, .btn-secondary:focus{
        background-color: #2b2a2a;
    }

    .card-header {
        text-align: center;
    }

    .footer {
        background-color: black; 
        color: white; 
        text-align: center; 
        padding: 20px;
    }

</style>

<nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="https://i.imgur.com/S4xLOxr.png" alt="Logo" class="d-inline-block align-text-top">
            Coffeeine.
        </a>
    </div>
</nav>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header"><h1>Your Coffee</h1></div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <table class="table">
                            {{ form.as_table }}
                            <tr>
                                <td></td>
                                <td>
                                    <input class="btn btn-primary" type="submit" value="Submit Changes">
                                    <a class="btn btn-secondary" href="{% url 'main:show_main' %}">Cancel</a>
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="footer">
    &copy; 2023 Coffeeine. All Rights Reserved.
</div>
{% endblock content %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

<style>
    .navbar {
        background-color: #000;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        padding: 20px 50px;
        margin-bottom: 40px;
    }

    .navbar-brand img {
        width: 80px; 
        height: 80px;
        margin-right: 10px; 
    }

    .navbar-brand {
        font-size: 60px;
        font-family: "EB Garamond", serif;
        color: #ffffff;
        text-align: center;
        padding-top: 10px;
    }

    .navbar-brand:hover {
        color: #ffffff;
    }

    .btn-primary {
        background-color: green;
        margin-bottom: 15px;
    }

    .btn-primary:hover, .btn-primary:active, .btn-primary:focus {
        background-color: darkgreen;
        border-color: darkgreen;
    }

    p {
        margin-top: 10px;
    }

</style>

    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="https://i.imgur.com/S4xLOxr.png" alt="Logo" class="d-inline-block align-text-top">
                Coffeeine.
            </a>
        </div>
    </nav>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h1 class="text-center">Login</h1>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="">
                            {% csrf_token %}
                            <div class="form-group mb-3">
                                <label for="username">Username:</label>
                                <input type="text" name="username" id="username" class="form-control" placeholder="Username">
                            </div>
                            <div class="form-group mb-3">
                                <label for="password">Password:</label>
                                <input type="password" name="password" id="password" class="form-control" placeholder="Password">
                            </div>
                            <div class="form-group text-center">
                                <input class="btn btn-primary" type="submit" value="Login">
                            </div>
                        </form>
                        {% if messages %}
                            <ul class="list-group">
                                {% for message in messages %}
                                    <li class="list-group-item">{{ message }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                        <p>Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}

<style>
    .navbar {
        background-color: #000;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        padding: 20px 50px;
        margin-bottom: 40px;
    }

    .navbar-brand img {
        width: 80px; 
        height: 80px;
        margin-right: 10px; 
    }

    .navbar-brand {
        font-size: 60px;
        font-family: "EB Garamond", serif;
        color: #ffffff;
        text-align: center;
        padding-top: 10px;
    }

    .navbar-brand:hover {
        color: #ffffff;
    }

    .btn-primary, .btn-primary:hover, .btn-primary:active, .btn-primary:focus {
        background-color: green;
    }

    table {
        width: 100%;
        border-collapse: collapse;
    }

    button {
        padding: 6px 12px;
        background-color: green;
        border: none;
        color: white;
        cursor: pointer;
        margin-right: 5px;
    }

    td {
        border: 1px solid #dddddd;
        padding: 8px;
        text-align: left;
        position: relative;
    }

    th {
        background-color: #f2f2f2;
        text-align: center;
        padding: 8px;
    }   

    tr:hover {
        background-color: #ddd;
    }

    #sapa, #sesi {
        font-size: 24px;
        text-align: center;
        margin-bottom: 10px;
    }

    #total {
        font-size: 18px;
        text-align: center;
        margin-bottom: 20px;
    }

    .button-container {
        text-align: center;
        margin-top: 10px;
        margin-bottom: 10px;
    }

    .custom-button {
        background-color: #eb8921;
        border-color: #eb8921;
        color: white;
        padding: 10px 20px;
        border: none;
        cursor: pointer;
        margin: 5px;
        border-radius: 5px;
    }

    .custom-button:hover, .custom-button:active, .custom-button:focus {
        background-color: #f5ad28;
        border-color: #f5ad28;
    }

    #button_add{
        background-color: green
    }

    #button_add:hover{
        background-color: darkgreen;
    }

    .logout-button {
        background-color: black;
        color: white;
        padding: 10px 20px;
        border: none;
        cursor: pointer;
        margin: 5px;
        border-radius: 5px;
    }

    .logout-button:hover, .logout-button:focus, .logout-button:active {
        background-color:#2b2a2a;
    }

    .card {
        width: 320px; /* Lebar kartu yang lebih besar */
        height: 320px; /* Tinggi kartu yang lebih besar */
        border-radius: 10px; /* Border melengkung */
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); /* Efek bayangan */
        margin: 10px; /* Jarak antara kartu */
        display: flex; /* Menyusun kartu dalam satu baris */
        overflow: hidden; /* Batasi overflow */
    }

    .card:hover .card-header, .card:hover .card-footer {
        background-color: rgb(243, 188, 86); /* Warna latar belakang saat hover */
    }

    .card:hover .card-body {
        background-color: rgb(234, 201, 141);
    }

    .card-body {
        padding: 10px;
    }

    .cards-container {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
    }

    .card-title {
        font-size: 20px;
        text-align: center;
        white-space: nowrap; /* Tidak ada wrap pada judul */
        overflow: hidden; /* Batasi judul yang panjang */
        text-overflow:ellipsis;
    }

    .card-footer {
        margin-top: auto;
    }
    
    .card-footer .btn.btn-primary {
        background-color: #eb8921;
        border-color: #eb8921;
    }
    .card-footer .btn.btn-primary:hover {
        background-color: #f5ad28;
        border-color: #f5ad28;
    }

    .card-footer .btn.btn-danger {
        background-color: black;
        border-color: black;
    }
    .card-footer .btn.btn-danger:hover {
        background-color: #2b2a2a;
        border-color: #2b2a2a;
    }

    .card-body .card-description {
        max-height: 200px; /* Tinggi maksimum deskripsi */
        overflow: hidden;
        display: -webkit-box;
        -webkit-line-clamp: 4; /* Menampilkan maksimum 3 baris teks */
        -webkit-box-orient: vertical;
    }

    .footer {
        background-color: black; 
        color: white; 
        text-align: center; 
        padding: 20px;
    }
    
</style>

    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="https://i.imgur.com/S4xLOxr.png" alt="Logo" class="d-inline-block align-text-top">
                Coffeeine.
            </a>
        </div>
    </nav>

    <h5 id="sapa" class="custom-heading">Halo {{name}} dari kelas {{class}}!</h5>

    {% with total_items=items|length %}
        <p id="total">☕ Anda menyimpan {{ total_items }} jenis kopi pada aplikasi ini ☕</p>
    {% endwith %}

    <div class="cards-container"></div>
    
    <h5 id="sesi" style="margin-top: 20px;">Sesi terakhir login: {{ last_login }}</h5>
    <br />

    <div class="button-container text-center">
        <button class="custom-button btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" id="openModal">
            Add New Item
        </button>
        
        <a href="{% url 'main:logout' %}" onclick="return confirm('Apakah Anda yakin ingin logout?');">
            <button class="custom-button logout-button">
                Logout
            </button>
        </a>
    </div>

    <div class="footer">
        &copy; 2023 Coffeeine. All Rights Reserved.
    </div>


    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add Your New Coffee</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="name" name="name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="price" class="col-form-label">Price:</label>
                            <input type="number" class="form-control" id="price" name="price"></input>
                        </div>
                        <div class="mb-3">
                            <label for="amount" class="col-form-label">Amount:</label>
                            <input type="number" class="form-control" id="amount" name="amount"></input>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" id="button_delete"data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Coffee</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        async function getItems() {
            return fetch("{% url 'main:get_item_json' %}").then((res) => res.json())
        }

        async function refreshItems() {
            const items = await getItems();
            const cardsContainer = document.querySelector(".cards-container");
            cardsContainer.innerHTML = "";

            items.forEach((item) => {
                const card = document.createElement("div");
                card.className = "card";
                card.innerHTML = `
                <header class="card-header">
                    <h5 class="card-title">${item.fields.name}</h5>
                </header>
                <div class="card-body">
                    <p class="card-text">Price: ${item.fields.price}</p>
                    <p class="card-text">Amount: ${item.fields.amount}</p>
                    <p class="card-description">Description: ${item.fields.description}</p>
                    </div>
                <div class="card-footer">
                    <a href="/edit-item/${item.pk}" class="btn btn-primary">Edit</a>
                    {% csrf_token %}
                        <button class="btn btn-secondary" onclick="incrementAmount(${item.pk})">+</button>
                        <button class="btn btn-secondary" onclick="decrementAmount(${item.pk})">-</button>
                        <a href="#" class="btn btn-danger" onclick="confirmDelete(${item.pk}); return false;">Delete</a>
                </div>
                `;
                cardsContainer.appendChild(card);
            });
        }

        function addItem() {
            fetch("{% url 'main:add_item_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshItems)

            document.getElementById("form").reset()
            return false
        }

        function incrementAmount(id) {
            fetch("/increment-item-ajax/?/".replace("?", id), {
                method: "POST"
            }).then(refreshItems)

            document.getElementById("form").reset()
            return false
        }

        function decrementAmount(id) {
            fetch("/decrement-item-ajax/?/".replace("?", id), {
                method: "POST"
            }).then(refreshItems)

            document.getElementById("form").reset()
            return false
        }

        async function confirmDelete(id) {
            if (confirm('Apakah Anda yakin ingin menghapus item ini?')) {
                deleteItem(id);
            }
        }

        function deleteItem(id) {
            fetch("/delete-item-ajax/?/".replace("?", id), {
                method: "POST"
            }).then(refreshItems)

            document.getElementById("form").reset()
            return false
        }

        refreshItems()
        document.getElementById("button_add").onclick = addItem
    </script>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  

<style>
    .navbar {
        background-color: #000;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        padding: 20px 50px;
        margin-bottom: 40px;
    }

    .navbar-brand img {
        width: 80px; 
        height: 80px;
        margin-right: 10px; 
    }

    .navbar-brand {
        font-size: 60px;
        font-family: "EB Garamond", serif;
        color: #ffffff;
        text-align: center;
        padding-top: 10px;
    }

    .navbar-brand:hover {
        color: #ffffff;
    }

    .btn-primary {
        background-color: green;
        border-color: green;
        margin-bottom: 15px;
    }

    .btn-primary:hover, .btn-primary:active, .btn-primary:focus {
        background-color: darkgreen;
        border-color: darkgreen;
    }

    p {
        margin-top: 10px;
    }

</style>

    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="https://i.imgur.com/S4xLOxr.png" alt="Logo" class="d-inline-block align-text-top">
                Coffeeine.
            </a>
        </div>
    </nav>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header text-center"><h1>Register</h1></div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-group mb-3">
                                {{ form.username.label_tag }}
                                <input type="text" name="{{ form.username.name }}" class="form-control" id="{{ form.username.id_for_label }}" required>
                            </div>
                            <div class="form-group mb-3">
                                {{ form.password1.label_tag }}
                                <input type="password" name="{{ form.password1.name }}" class="form-control" id="{{ form.password1.id_for_label }}" required>
                            </div>
                            <div class="form-group mb-3">
                                {{ form.password2.label_tag }}
                                <input type="password" name="{{ form.password2.name }}" class="form-control" id="{{ form.password2.id_for_label }}" required>
                            </div>
                            <div class="form-group text-center">
                                <input class="btn btn-primary" type="submit" name="submit" value="Register">
                            </div>
                        </form>
                        {% if messages %}
                            <ul class="list-group">
                                {% for message in messages %}
                                    <li class="list-group-item">{{ message }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}